### ISSUE TITLE
Missing dataset

### ISSUE THREAD

**Issue by zhouyaguang** [ehtesam3154/dgs_svdd#1]
The dataset file is missing, causing the program to not run properly. Please supplement the dataset, thank you!

**Comment by ehtesam3154** [comment]
kindly check the dataset[ here](https://knightsucfedu39751-my.sharepoint.com/:f:/g/personal/azim_ehtesam_knights_ucf_edu/Eh2_h1sihzNBk6ENqLVNm_0B9O3NwGMGC3DoMI7THIGUEg?e=6OSerV) 

it's the swat dataset, it's widely available online btw

**Comment by zhouyaguang** [comment]
Thank you very much for sharing the two dataset files, which allowed me to reproduce the basic logic of the codes and most of the results. But I still encountered a problem during the replication process. Your code (named “graph_embeddings_ehtesam.ipynb”) contains codes to load file whose name is “adjacentMatrix.npz”. However, this file is a unique file that was not included in the SWaT dataset and may have been manually processed by you during the coding process. Sharing this dataset would be very helpful for reproducing these codes, and  thank you your contribution in this field.

**Comment by ehtesam3154** [comment]
Really sorry I missed that. It should be available now. I'll clean up this repo later sometime hopefully

**Comment by zhouyaguang** [comment]
Thank you very much for your generous sharing, which helped me successfully reproduce your code. Your research has made significant contributions in the field of anomaly detection research, and I will cite and highly praise your work in the paper I am currently writing. Thank you again for your research and wish you a nice day!

**Comment by zhouyaguang** [comment]
The dataset has been generously shared by the author in the one drive link, so the program can be fully reproduced. Thanks a lot for the author's help!

**Comment by Candy8038** [comment]
> Really sorry I missed that. It should be available now. I'll clean up this repo later sometime hopefully

Could you please share this file with me as well? Thank you very much!

**Comment by ehtesam3154** [comment]
> > Really sorry I missed that. It should be available now. I'll clean up this repo later sometime hopefully
> 
> Could you please share this file with me as well? Thank you very much!

Hi Candy8038, unfortunately I am unable to access the dataset link myself because my university updated their email system and everything after Fall 2023. Could you kindly refer to the readme for the dataset ? The owners are quite fast with their response, you only should have to fill up a google form.

**Comment by Candy8038** [comment]
> > > Really sorry I missed that. It should be available now. I'll clean up this repo later sometime hopefully
> > 
> > 
> > Could you please share this file with me as well? Thank you very much!
> 
> Hi Candy8038, unfortunately I am unable to access the dataset link myself because my university updated their email system and everything after Fall 2023. Could you kindly refer to the readme for the dataset ? The owners are quite fast with their response, you only should have to fill up a google form.

Thank you for your reply. I have obtained the dataset files through official channels, but I could not find the “adjacentMatrix.npz” in the official dataset. Could you please share this file? Thank you！

**Comment by ehtesam3154** [comment]
> > > > Really sorry I missed that. It should be available now. I'll clean up this repo later sometime hopefully
> > > 
> > > 
> > > Could you please share this file with me as well? Thank you very much!
> > 
> > 
> > Hi Candy8038, unfortunately I am unable to access the dataset link myself because my university updated their email system and everything after Fall 2023. Could you kindly refer to the readme for the dataset ? The owners are quite fast with their response, you only should have to fill up a google form.
> 
> Thank you for your reply. I have obtained the dataset files through official channels, but I could not find the “adjacentMatrix.npz” in the official dataset. Could you please share this file? Thank you！

had to dig through a lot of old files but I have uploaded it here: [mega link](https://mega.nz/folder/v2JlGBZK#nuD3dar1JXJwm5W38qDeOw)

**Comment by Candy8038** [comment]
> > > > > Really sorry I missed that. It should be available now. I'll clean up this repo later sometime hopefully
> > > > 
> > > > 
> > > > Could you please share this file with me as well? Thank you very much!
> > > 
> > > 
> > > Hi Candy8038, unfortunately I am unable to access the dataset link myself because my university updated their email system and everything after Fall 2023. Could you kindly refer to the readme for the dataset ? The owners are quite fast with their response, you only should have to fill up a google form.
> > 
> > 
> > Thank you for your reply. I have obtained the dataset files through official channels, but I could not find the “adjacentMatrix.npz” in the official dataset. Could you please share this file? Thank you！
> 
> had to dig through a lot of old files but I have uploaded it here: [mega link](https://mega.nz/folder/v2JlGBZK#nuD3dar1JXJwm5W38qDeOw)

Thank you very much for your reply and your sharing. Wishing you good health and all the best!
